### ISSUE TITLE
Not able to process data

### ISSUE THREAD

**Issue by shantanuo** [msiemens/HypheNN-de#1]
Not able to prepare the data because I do not know anything about rust. In other words this command returns an error.

$ cargo run --release ../data/dewiktionary-*-pages-articles.xml ../wordlist.txt

Is there any other way to achieve this? Or can you share the wordlist.txt file?

**Comment by shantanuo** [comment]
I managed to create the wordlist. Thanks for this useful repository.

**Comment by msiemens** [comment]
Hey! What was the exact error you had? And what was the solution? Maybe it could help others who might have the same issue 🙃
